# Generated by Django 5.0.2 on 2024-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
